export default {
  'base': [
    {
      label: '文本',
      key: '',
      icon: 'label',
      type: 'label',
      class: '',
      default: '默认文本',
      labelWidth: '100px'
    },
    {
      label: '单行文本', 
      key: '',
      icon: 'input', 
      type: 'input', 
      class: '',
      default: '',
      labelWidth: '100px',
      width: '100%',
      placeholder: '',
      options_clearable: false,
      options_disabled: false, 
      validate_required: false,
      validate_rules: [], 
    },
    {
      label: '选择器',
      key: '',
      icon: 'selector',
      type: 'select',
      class: '',
      // default: [],
      labelWidth: '100px',
      placeholder: '',
      options: [
        // {label: 'option1', value: 'option1'},
      ],
      options_filterable: false,
      options_multiple: false,
      options_remote: false,
      options_clearable: false,
      options_disabled: false,
      validate_required: false,
      validate_rules: [],
    },
    {
      label: '日期选择器',
      key: '',
      icon: 'date-time',
      type: 'datePicker',
      default: '',
      class: '',
      labelWidth: '100px',
      widgetType: 'datetime',
      valueFormat: 'yyyy-MM-dd HH:mm:ss',
      placeholder: '',
      options_clearable: false,
      options_disabled: false,
      validate_required: false,
      validate_rules: [],
    },
    {
      label: '时间选择器',
      key: '',
      icon: 'time',
      type: 'timePicker',
      class: '',
      default: '',
      labelWidth: '100px',
      valueFormat: 'HH:mm:ss',
      placeholder: '',
      options_clearable: false,
      options_disabled: false,
      validate_required: false,
      validate_rules: [],
    },
    {
      label: '拾色器',
      key: '',
      icon: 'color-picker',
      type: 'colorPicker',
      class: '',
      default: '',
      labelWidth: '100px',
      colorFormat: 'hex',
      options_showAlpha: false,
      options_disabled: false,
      validate_required: false,
      validate_rules: [],
    }
  ],
  'advance': [
    {
      label: '自定义组件',
      key: '',
      icon: 'custom',
      type: 'custom',
      class: '',
      labelWidth: '100px',
    }
  ],
  'layout': [
    {
      label: '栅格', 
      key: '',
      icon: 'grid', 
      type: 'grid', 
      gutter: '0', 
      columns: [
        {colSpan: 12, list: []},
        {colSpan: 12, list: []},
      ]
    }
  ]
}